
// Generated by Redwood - Do not modify this file
class TaskListViewModel {

    public Tasks = ko.observableArray<Task>();

}

class Task {

    public Title = ko.observable<string>();

}


