
// Generated by Redwood - Do not modify this file
class IndexViewModel {

    public NewTaskText = ko.observable<string>();

    public Tasks = ko.observableArray<Task>();

    public AddTask(element: HTMLElement, arguments: any[]): void {
Redwood.PostBack(element, 'AddTask', arguments);
    }

    public FinishTask(element: HTMLElement, arguments: any[]): void {
Redwood.PostBack(element, 'FinishTask', arguments);
    }

}

class Task {

    public Title = ko.observable<string>();

}


