// Generated by Redwood - Do not modify this file
var TaskListViewModel = (function () {
    function TaskListViewModel() {
        this.Tasks = ko.observableArray();
    }
    return TaskListViewModel;
})();

var Task = (function () {
    function Task() {
        this.Title = ko.observable();
    }
    return Task;
})();
//# sourceMappingURL=Data.js.map
