// Generated by Redwood - Do not modify this file
var IndexViewModel = (function () {
    function IndexViewModel() {
        this.NewTaskText = ko.observable();
        this.Tasks = ko.observableArray();
    }
    IndexViewModel.prototype.AddTask = function (element, arguments) {
        Redwood.PostBack(element, 'AddTask', arguments);
    };

    IndexViewModel.prototype.FinishTask = function (element, arguments) {
        Redwood.PostBack(element, 'FinishTask', arguments);
    };
    return IndexViewModel;
})();

var Task = (function () {
    function Task() {
        this.Title = ko.observable();
    }
    return Task;
})();
//# sourceMappingURL=Data.js.map
